### ISSUE TITLE
{Feature Request} Follow transport from one HyperDeck 

### ISSUE THREAD

**Issue by MDAR** [cjellison90/panel-for-hyperdeck#1]
We have a situation where we'd like to use the hardware controls on one HyperDeck (for example the jog wheel on a Shuttle HD) and have other HyperDecks follow.

Is this something we could use HyperDeckPanel for?

The use case is

Multiple HyperDecks recording rehearsal cameras, so that the show tech can be programmed in sync.

The tech programming & rehearsals then don't need the performers on stage, a tech can simply shuttle the HyperDecks to find the time code for the cue points.

********

Alternatively

Is there any way to use a hardware transport controller?

Examples

https://backcareonline.co.uk/contour-multimedia-controller-formerly-shuttle-xpress-v2

https://www.amazon.co.uk/Controller-Vaydeer-Multimedia-Controll-Function-black/dp/B08V4ZB5MV/

https://www.amazon.co.uk/Contour-00496-0-Design-ShuttleXpress-Black/dp/B0032Y0OH0/

**Comment by cjellison90** [comment]
Panel for HyperDeck isn't a real-time tool, so it wouldn't be able to keep multiple decks in sync.

The tech could use one deck to seek to the cue point, copy the timecode from that deck into the Sync timecode, and assuming the other decks were configured to be synced together, that would get the decks to the same point. At that point, the tech could hit play in the sync row and start all of the decks together.

If the tech does need all decks to be in sync during a shuttle operation, then a hardware panel (like the HyperDeck Extreme Control or similar) would allow for that.

**Comment by MDAR** [comment]
Hello 👋 

Thank you for taking the time to reply and fill in the blanks for me.


> If the tech does need all decks to be in sync during a shuttle operation, then a hardware panel (like the HyperDeck Extreme Control or similar) would allow for that.

I knew something like this had to exist, I just hadn't been pointed in the right direction.

https://www.blackmagicdesign.com/uk/products/hyperdeckextreme/control

I think this bit of kit will be perfect.

Thanks again.
